### your site title here

title: Bhaskar Ram
description: Hacker & Dev | Affiliations | Motto

baseurl: /bhaskarvilles #name of GitHub repository
url: "https://bhaskarvilles.dev" #custom url to be used instead of GitHub repository
email: bhaskar@parrotsec.in


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
facebook: "https://facebook.com/bhaskarvilles"
twitter: "https://twitter.com/bhaskarvilles"
linkedin: "https://linkedin.com/bhaskarvilles"
github: "https://github.com/bhaskarvilles"
researchgate: "#"
orcid: "#"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
